services:
  - type: web
    name: dr-jii-model
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd backend && python main.py"
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: PYTHON_VERSION
        value: 3.11.0